In [1]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline  

In [7]:
class periodic_conv2dmodel(tf.keras.Model):
    def __init__(self):
        super(periodic_conv2dmodel, self).__init__()

        self.pre = tf.constant([[0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]])
        self.post = tf.transpose(self.pre)

        self.Con2DLayer = tf.keras.layers.Conv2D(5, (3, 3), activation='linear', padding='same') 
        
    def call(self, X):
#         periodically_padded = tf.matmul(tf.matmul(self.pre, X), self.post)
        periodically_padded = tf.reshape(X , (1,3,3,1) )
        output = self.Con2DLayer (periodically_padded)

        return outputs

In [8]:
feature_map = tf.constant([[1,2,3],[4,5,6],[7,8,9]]) 
print feature_map

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [9]:
model = periodic_conv2dmodel()

In [10]:
model(feature_map)

InvalidArgumentError: Need minval < maxval, got 0 >= 0 [Op:RandomUniformInt] name: periodic_conv2dmodel_1/conv2d_1/kernel/random_uniform/